### ISSUE TITLE
unbound version constraints (@stable) should be avoided

### ISSUE THREAD

**Issue by sasezaki** [o0h/php-ast-check-diff#6]
```
composer validate
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# General warnings
- require.symfony/polyfill-php83 : unbound version constraints (@stable) should be avoided
```

Please consider specify version, instead of `@stable`.
Using `@stable` is fragile.

**Comment by o0h** [comment]
@sasezaki 
Thank you! I'm very pleased to receive feedback that makes this project feel safer to use.

* First, regarding the `symfony/polyfill-php83` in `require`, as mentioned in #7, I intend to remove it.
* As for the use of `@stable` in `require-dev`, I plan to maintain the current situation
    * Indeed, allowing versions to update without limit could potentially lead to breaking changes in the future.
    * However, I believe we can control the risk of operational breakage through the use of .lock files to manage versions.
* Why do I want to use the latest stable versions indiscriminately? The most accurate answer might be that it's a matter of personal preference.
    * Instead, I would like to focus on keeping the tool itself lean and enhancing end-to-end level testing.

**Comment by o0h** [comment]
There are still some @stable tags left in the require-dev packages, but with this change, I have removed all ambiguous versions from the require packages. 
I will continue to ensure the reliability of the development tools packages by keeping the composer.lock file updated and running E2E-level tests in my continuous integration process.
